name: "Build"
on: "push"
jobs:
  Build-Server-Jar:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
      - run: gradlew
